import {spaceRail} from './space-controls.js';
spaceRail();
const $=(q,root=document)=>root.querySelector(q);
const $$=(q,root=document)=>[...root.querySelectorAll(q)];
const safe=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage={get(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set(key,value){localStorage.setItem(key,JSON.stringify(value))}};
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const themeButton=$('.theme-toggle');
function syncTheme(){const light=document.documentElement.dataset.theme==='light';themeButton.setAttribute('aria-label',light?'Koyu temaya geç':'Açık temaya geç');themeButton.title=light?'Işıkları kapat':'Işıkları aç';$('.theme-icon').textContent=light?'☾':'☼';$('meta[name="theme-color"]').content=light?'#f5f3ee':'#111113';}
themeButton.addEventListener('click',async()=>{if(document.documentElement.classList.contains('theme-changing'))return;const theme=document.documentElement.dataset.theme==='light'?'dark':'light';const r=themeButton.getBoundingClientRect();document.documentElement.style.setProperty('--theme-x',r.left+r.width/2+'px');document.documentElement.style.setProperty('--theme-y',r.top+r.height/2+'px');const change=()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('ey-theme',theme)}catch{}syncTheme();dispatchEvent(new CustomEvent('ey-theme-change'));};if(document.startViewTransition&&!reducedMotion.matches){document.documentElement.classList.add('theme-changing');try{const transition=document.startViewTransition(change);transition.ready.catch(()=>{});await transition.finished}catch{}finally{document.documentElement.classList.remove('theme-changing')}}else change();});syncTheme();
const menu=$('.menu-toggle'),mobileMenu=$('#mobile-menu');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Menüyü aç');mobileMenu.hidden=true;}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Menüyü kapat':'Menüyü aç');mobileMenu.hidden=!open;});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
mobileMenu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});
matchMedia('(min-width: 801px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
function tickTime(){const time=$('.local-time');if(time)time.textContent=new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'}).format(new Date());}tickTime();setInterval(tickTime,60000);
let observer;if('IntersectionObserver'in window&&!reducedMotion.matches){document.body.classList.add('motion-ready');observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.06});}
function observe(root=document){if(observer)$$('.reveal',root).forEach(el=>observer.observe(el));}observe();
let scrollPending=false;function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;$('.page-progress').style.width=(max>0?scrollY/max*100:0)+'%';scrollPending=false;}
addEventListener('scroll',()=>{if(!scrollPending){scrollPending=true;requestAnimationFrame(updateProgress)}},{passive:true});addEventListener('resize',updateProgress);updateProgress();
function setupLogos(root=document){$$('.logo-tile',root).forEach(tile=>{tile.addEventListener('click',()=>{const on=tile.getAttribute('aria-pressed')!=='true';tile.setAttribute('aria-pressed',String(on));tile.setAttribute('aria-label',tile.getAttribute('aria-label').replace(on?'orijinal renkleriyle':'tek renk görünümde',on?'tek renk görünümde':'orijinal renkleriyle'));});});}setupLogos();
const dialog=$('#image-dialog');
$$('[data-zoom]').forEach(button=>button.addEventListener('click',()=>{const im=$('img',dialog);im.src=button.dataset.zoom;im.alt=button.dataset.caption;$('p',dialog).textContent=button.dataset.caption;dialog.showModal();}));
$('.dialog-close',dialog).addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
$$('[data-project-filter]').forEach(button=>button.addEventListener('click',()=>{const selected=button.dataset.projectFilter;$$('[data-project-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});let count=0;$$('#reference-grid .project-card').forEach(card=>{card.hidden=selected!=='all'&&card.dataset.filter!==selected;if(!card.hidden)count++});$('.result-count').textContent=count+' çalışma';}));
const contact=$('#contact-form');
contact?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(contact);const name=data.get('name').trim(),email=data.get('email').trim(),message=data.get('message').trim();if(!name||!message){$('#form-status').textContent='Adınızı ve mesajınızı yazın.';return;}const subject=data.get('subject');const text=`Merhaba Enes,\n\n${subject}\n\n${message}\n\n${name}\n${email}`;if(e.submitter?.value==='whatsapp'){window.open('https://wa.me/905357023316?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');$('#form-status').textContent='WhatsApp bağlantısı açıldı. Mesajı WhatsApp’ta gönderebilirsiniz.';}else{location.href='mailto:ensylmz34@gmail.com?subject='+encodeURIComponent(subject+' · '+name)+'&body='+encodeURIComponent(text);$('#form-status').textContent='Mesaj e-posta uygulamanız için hazırlandı. Uygulama açılmadıysa doğrudan e-posta bağlantısını kullanabilirsiniz.';}});

// Perspective-projected torus. No external 3D runtime or model download.
const canvas=$('#orbital-canvas');
if(canvas){const ctx=canvas.getContext('2d');if(ctx){let width=0,height=0,visible=true,frame=0,last=0;const pointer={x:0,y:0};const points=[];for(let a=0;a<100;a++)for(let b=0;b<20;b++){const u=a/100*Math.PI*2,v=b/20*Math.PI*2,r=1.03+.3*Math.cos(v);points.push({x:r*Math.cos(u),y:r*Math.sin(u),z:.3*Math.sin(v),v});}
 const resize=()=>{const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(devicePixelRatio,1.7);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw(performance.now());};
 function project(x,y,z,rx,ry,rz){let cy=Math.cos(rx),sy=Math.sin(rx),ny=y*cy-z*sy,nz=y*sy+z*cy;y=ny;z=nz;cy=Math.cos(ry);sy=Math.sin(ry);let nx=x*cy+z*sy;nz=-x*sy+z*cy;x=nx;z=nz;cy=Math.cos(rz);sy=Math.sin(rz);nx=x*cy-y*sy;ny=x*sy+y*cy;const factor=3.8/(3.8-z);const size=Math.min(width,height)*.3;return{x:width*.5+nx*size*factor,y:height*.49+ny*size*factor,z,s:factor};}
 function draw(t){if(!width||!height)return;ctx.clearRect(0,0,width,height);const light=document.documentElement.dataset.theme==='light';const time=reducedMotion.matches?0:t*.00013;const rx=.85+pointer.y*.12,ry=-.42+Math.sin(time)*.2+pointer.x*.16,rz=-.42+time*.22+Math.min(scrollY,800)*.00017;const coords=points.map(p=>({...project(p.x,p.y,p.z,rx,ry,rz),v:p.v})).sort((a,b)=>a.z-b.z);const glow=ctx.createRadialGradient(width*.5,height*.49,0,width*.5,height*.49,Math.min(width,height)*.43);glow.addColorStop(0,light?'rgba(182,59,29,.035)':'rgba(255,112,73,.055)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);
 ctx.strokeStyle=light?'rgba(182,59,29,.2)':'rgba(255,112,73,.2)';ctx.lineWidth=.7;for(let ring=0;ring<2;ring++){ctx.beginPath();for(let a=0;a<=150;a++){const u=a/150*Math.PI*2,r=1.65+ring*.2;const p=project(r*Math.cos(u),r*Math.sin(u),0,rx+ring*.5,ry-.3,rz);a?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.stroke();}
 for(const p of coords){const depth=(p.z+1.4)/2.8;ctx.globalAlpha=.22+depth*.75;ctx.fillStyle=light?(p.z>.1?'#b63b1d':'#7f7971'):(p.z>.1?'#ff956c':'#ad5141');ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.45,p.s*(p.z>.2?1.4:1)),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
 for(let a=0;a<3;a++){const u=time*(a%2?-.6:.5)+a*2.1;const p=project(1.75*Math.cos(u),1.75*Math.sin(u),0,rx+.5,ry-.3,rz);ctx.fillStyle=light?'#b63b1d':'#ffb294';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}
 }
 function animate(t){frame=requestAnimationFrame(animate);if(!visible||document.hidden||reducedMotion.matches)return;if(t-last>32){draw(t);last=t;}}
 new ResizeObserver(resize).observe(canvas);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting}).observe(canvas);canvas.parentElement.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;});canvas.parentElement.addEventListener('pointerleave',()=>{pointer.x=pointer.y=0});new MutationObserver(()=>draw(performance.now())).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});reducedMotion.addEventListener('change',()=>draw(performance.now()));resize();frame=requestAnimationFrame(animate);addEventListener('pagehide',event=>{if(!event.persisted)cancelAnimationFrame(frame)});}}

// Local draft workspace. No authentication or publishing claims.
const draftKey='ey-local-drafts-v1';
const emptyDrafts=()=>({projects:[],logos:[]});
function readDrafts(){const d=storage.get(draftKey,emptyDrafts());try{return validateDrafts(d)}catch{return emptyDrafts()}}
function dataImage(value){return typeof value==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(value)&&value.length<2900000;}
function validateDrafts(data){if(!data||!Array.isArray(data.projects)||!Array.isArray(data.logos)||data.projects.length+data.logos.length>30)throw Error('Geçerli bir taslak yedeği seçin (en fazla 30 kayıt).');const str=(v,max=1500)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Taslak alanlarını kontrol edin.');return v.trim();};const projects=data.projects.map(p=>{if(!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(p.slug)||p.slug.length>100||!['web','seo','commerce','design'].includes(p.filter)||!dataImage(p.cover)||!dataImage(p.logo))throw Error('Proje görseli veya URL adı geçersiz.');return{slug:p.slug,brand:str(p.brand,100),title:str(p.title,150),filter:p.filter,period:str(p.period,150),summary:str(p.summary),role:str(p.role),cover:p.cover,logo:p.logo};});if(new Set(projects.map(p=>p.slug)).size!==projects.length)throw Error('Aynı URL adına sahip iki taslak olamaz.');const logos=data.logos.map(l=>{if(!dataImage(l.image))throw Error('Logo görseli geçersiz.');return{name:str(l.name,100),category:str(l.category,100),image:l.image};});return{projects,logos};}
function saveDrafts(d){storage.set(draftKey,validateDrafts(d));}
const draftCard=p=>`<a class="project-card reveal local-card" data-filter="${safe(p.filter)}" href="/projeler/taslak/?id=${encodeURIComponent(p.slug)}"><div class="project-visual"><img src="${p.cover}" alt="${safe(p.brand)} taslak görseli" loading="lazy"><span class="project-number">YEREL TASLAK</span><span class="round-arrow">↗</span></div><div class="project-info"><div><span class="micro">${safe(p.brand)}</span><h3>${safe(p.title)}</h3></div><span class="project-year">${safe(p.period)}</span></div></a>`;
const drafts=readDrafts();
if($('#reference-grid')&&drafts.projects.length){const grid=$('#reference-grid');grid.insertAdjacentHTML('afterbegin',drafts.projects.map(draftCard).join(''));grid.insertAdjacentHTML('beforebegin','<p class="draft-banner">Bu tarayıcıdaki yerel taslaklar da gösteriliyor. Henüz yayımlanmadılar.</p>');$('.result-count').textContent=$$('#reference-grid .project-card').length+' çalışma';observe(grid);}
if(location.pathname==='/calismalar/'&&drafts.logos.length){const grid=$('.logo-grid');grid.insertAdjacentHTML('afterbegin',drafts.logos.map(l=>`<button class="logo-tile reveal local-logo" type="button" aria-pressed="false" aria-label="${safe(l.name)} logosunu orijinal renkleriyle göster"><div class="logo-image"><img src="${l.image}" alt="${safe(l.name)}" loading="lazy"></div><div class="logo-meta"><span>${safe(l.name)}</span><small>${safe(l.category)} · yerel taslak</small><span>↗</span></div></button>`).join(''));setupLogosForNew();observe(grid);function setupLogosForNew(){$$('.local-logo',grid).forEach(tile=>tile.addEventListener('click',()=>tile.setAttribute('aria-pressed',String(tile.getAttribute('aria-pressed')!=='true'))));}}
if($('#draft-project')){const slug=new URLSearchParams(location.search).get('id');const p=drafts.projects.find(p=>p.slug===slug);const area=$('#draft-project');if(p){area.innerHTML=`<p class="draft-banner">Yerel taslak · yalnızca bu tarayıcıda görünür.</p><span class="micro">${safe(p.brand)} / ${safe(p.period)}</span><h1>${safe(p.title)}</h1><p>${safe(p.summary)}</p><div class="project-cover"><img src="${p.cover}" alt="${safe(p.title)}"></div><h2>Benim rolüm</h2><p>${safe(p.role)}</p><a class="text-link" href="/panel/">Taslak paneline dön ↗</a>`;}else{area.innerHTML='<h1>Taslak bulunamadı.</h1><p>Bu taslak başka bir tarayıcıda oluşturulmuş olabilir.</p><a class="button solid" href="/panel/">Taslak paneli ↗</a>';}}
const adminStatus=$('#admin-status');
if(adminStatus){const projectForm=$('#project-draft-form'),logoForm=$('#logo-draft-form');const showStatus=text=>{adminStatus.textContent=text;};
 function list(){const d=readDrafts(),area=$('#draft-list');area.innerHTML=d.projects.map((p,i)=>`<div class="draft-entry"><div>${safe(p.brand)}<small>Referans taslağı</small></div><button data-delete="project:${i}" aria-label="${safe(p.brand)} taslağını kaldır">Kaldır</button></div>`).join('')+d.logos.map((l,i)=>`<div class="draft-entry"><div>${safe(l.name)}<small>Logo taslağı</small></div><button data-delete="logo:${i}" aria-label="${safe(l.name)} taslağını kaldır">Kaldır</button></div>`).join('');if(!area.children.length)area.innerHTML='<p>Henüz yerel taslak yok.</p>';$$('[data-delete]',area).forEach(button=>button.addEventListener('click',()=>{const [type,index]=button.dataset.delete.split(':');const data=readDrafts();data[type==='project'?'projects':'logos'].splice(Number(index),1);try{saveDrafts(data);list();showStatus('Taslak kaldırıldı.')}catch{showStatus('Tarayıcı kaydı güncellenemedi.')}}));}list();
 $$('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>{$$('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b===button));projectForm.hidden=button.dataset.adminTab!=='project';logoForm.hidden=!projectForm.hidden;}));
 const fileData=file=>new Promise((resolve,reject)=>{if(!(file instanceof File)||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024||file.size===0){reject(Error('PNG, JPG veya WebP seçin; her görsel en fazla 2 MB olabilir.'));return;}const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Görsel okunamadı.'));reader.readAsDataURL(file);});
 projectForm.addEventListener('submit',async e=>{e.preventDefault();const b=$('button[type=submit]',projectForm);b.disabled=true;try{const f=new FormData(projectForm),d=readDrafts();const slug=f.get('slug').trim();const shipped=await fetch('/assets/content.json').then(r=>r.json());if(shipped.projects.some(p=>p.slug===slug)||d.projects.some(p=>p.slug===slug)||slug==='taslak')throw Error('Bu URL adı kullanılıyor; farklı bir proje URL adı yazın.');d.projects.push({brand:f.get('brand').trim(),title:f.get('title').trim(),slug,filter:f.get('filter'),period:f.get('period').trim(),summary:f.get('summary').trim(),role:f.get('role').trim(),cover:await fileData(f.get('cover')),logo:await fileData(f.get('logo'))});saveDrafts(d);projectForm.reset();list();showStatus('Referans taslağı kaydedildi. Referanslar sayfasında önizleyebilirsiniz.');}catch(err){showStatus(err.name==='QuotaExceededError'?'Tarayıcı alanı doldu. Daha küçük görseller kullanın veya JSON yedeğini alıp taslakları azaltın.':err.message);}finally{b.disabled=false;}});
 logoForm.addEventListener('submit',async e=>{e.preventDefault();const b=$('button[type=submit]',logoForm);b.disabled=true;try{const f=new FormData(logoForm),d=readDrafts();d.logos.push({name:f.get('name').trim(),category:f.get('category').trim(),image:await fileData(f.get('image'))});saveDrafts(d);logoForm.reset();list();showStatus('Logo taslağı kaydedildi. Çalışmalar sayfasında önizleyebilirsiniz.');}catch(err){showStatus(err.name==='QuotaExceededError'?'Tarayıcı alanı doldu. Daha küçük bir görsel kullanın.':err.message);}finally{b.disabled=false;}});
 $('#export-drafts').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(readDrafts(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ensylmz-taslaklar-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showStatus('JSON yedeği indirildi.');});
 $('#import-drafts').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Yedek en fazla 10 MB olabilir.');const imported=validateDrafts(JSON.parse(await file.text()));const existing=readDrafts();const known=new Set(existing.projects.map(p=>p.slug));const merged={projects:[...existing.projects,...imported.projects.filter(p=>!known.has(p.slug))],logos:[...existing.logos,...imported.logos.filter(l=>!existing.logos.some(x=>x.name===l.name&&x.image===l.image))]};saveDrafts(merged);list();showStatus('Yedek mevcut taslaklarla birleştirildi.');}catch(err){showStatus(err.name==='QuotaExceededError'?'Tarayıcı alanı doldu. Daha küçük bir yedek kullanın.':'Yedek yüklenemedi: '+err.message);}e.target.value='';});}


