const area=document.querySelector('#persistent-panel');
if(area){
 const status=document.querySelector('#panel-message');const say=t=>status.textContent=t;
 async function api(url,data){const r=await fetch(url,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const json=await r.json();if(!r.ok)throw Error(json.error||'İşlem tamamlanamadı.');return json;}
 const fileData=file=>new Promise((resolve,reject)=>{if(!file||!file.size||file.size>2097152)return reject(Error('Her görsel en fazla 2 MB olmalı.'));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
 async function refresh(){const d=await api('/api/panel');const list=document.querySelector('#saved-entries');list.replaceChildren();for(const p of d.projects){const a=document.createElement('a');a.className='text-link';a.href='/projeler/'+p.slug+'/';a.textContent=p.brand+' · Sayfayı aç ↗';list.append(a);}for(const l of d.logos){const p=document.createElement('p');p.textContent=l.name+' · Logo kaydedildi';list.append(p);}if(!list.children.length)list.textContent='Henüz panelden kayıt eklenmedi.';}
 for(const form of area.querySelectorAll('form'))form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{say('Görseller kaydediliyor ve sayfalar oluşturuluyor…');const f=new FormData(form),data=Object.fromEntries([...f].filter(([,v])=>typeof v==='string'));data.type=form.dataset.type;for(const key of data.type==='logo'?['image']:['cover','logo'])data[key]=await fileData(f.get(key));if(data.type==='project'){data.gallery=[];for(const [i,file]of [...f.getAll('gallery')].filter(f=>f.size).entries())data.gallery.push({image:await fileData(file),caption:data.brand+' · çalışma görseli '+(i+1)});}await api('/api/panel',data);form.reset();await refresh();say('Kaydedildi. Referansın ayrı proje sayfası hazır; GitHub’a göndererek yayımlayabilirsin.');}catch(e){say(e.message)}finally{button.disabled=false}});
 const tokenField=document.createElement('input');tokenField.type='password';tokenField.autocomplete='off';tokenField.placeholder='github_pat_…';tokenField.id='github-token';const tokenLabel=document.createElement('label');tokenLabel.textContent='GitHub erişim anahtarı · her gönderimde gerekli';tokenLabel.append(tokenField);document.querySelector('#publish-github').before(tokenLabel);
 document.querySelector('#publish-github').addEventListener('click',async e=>{const token=tokenField.value.trim();if(!token){say('Göndermeden önce GitHub erişim anahtarını gir.');tokenField.focus();return;}e.target.disabled=true;tokenField.value='';try{say('Anahtar doğrulanıyor ve site GitHub’a gönderiliyor…');await api('/api/publish',{token});say('GitHub’a gönderildi. Yayın durumunu GitHub Actions bölümünden takip edebilirsin.');}catch(err){say(err.message)}finally{e.target.disabled=false}});
 refresh().catch(()=>{say('Bu panel bilgisayarındaki BASLAT ile çalışır. Canlı site üzerinden dosya kaydı yapılamaz.');area.querySelectorAll('button').forEach(b=>b.disabled=true)});
}
