import {createRequire} from 'node:module';import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await fs.mkdir('qa/v7',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const checks=[],errors=[];const ok=(v,n)=>{if(!v)throw Error(n);checks.push(n)};
async function load(context){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>sessionStorage.setItem('ey-arrival-v5','1'));await p.goto('http://127.0.0.1:4173/');await p.waitForSelector('.core-journey');return p;}
const ctx=await browser.newContext({viewport:{width:1440,height:900}}),p=await load(ctx);
for(const [i,n] of [.1,.3,.5,.7,.98].entries()){await p.locator('.core-journey').evaluate((e,n)=>scrollTo(0,e.getBoundingClientRect().top+scrollY+(e.offsetHeight-innerHeight)*n),n);await p.waitForTimeout(1000);ok(await p.locator('.core-journey').getAttribute('data-phase')===String(i),'Core phase '+i);await p.screenshot({path:`qa/v7/core-${i}.png`});}
const card=p.locator('.story-card').first(),visual=card.locator('.project-visual');await card.evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-20));await p.mouse.move(5,5);await p.waitForTimeout(800);ok(!await visual.evaluate(e=>e.classList.contains('portal-open')),'Orange cover closed');await p.screenshot({path:'qa/v7/orange-project.png'});await visual.hover();await p.waitForTimeout(900);ok(await visual.evaluate(e=>e.classList.contains('portal-open')),'Hover reveals project');await p.screenshot({path:'qa/v7/open-project.png'});await p.mouse.move(5,5);await p.waitForTimeout(800);ok(!await visual.evaluate(e=>e.classList.contains('portal-open')),'Cover restores');
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),m=await load(mobile);const mv=m.locator('.story-card .project-visual').first();await mv.scrollIntoViewIfNeeded();await mv.tap();ok(m.url().endsWith(':4173/'),'Touch stays on home');ok(await mv.evaluate(e=>e.classList.contains('portal-open')),'Touch reveals');ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile width fits');await m.screenshot({path:'qa/v7/mobile-project.png'});await m.locator('.story-card .project-discover').first().tap();await m.waitForURL('**/proje*/**');ok(true,'Project CTA navigates');
const reduced=await browser.newContext({viewport:{width:320,height:740},reducedMotion:'reduce'}),r=await load(reduced);await r.locator('.core-journey').scrollIntoViewIfNeeded();ok(await r.locator('.core-stage').evaluate(e=>getComputedStyle(e).position==='relative'),'Reduced motion has no pinned sequence');ok(await r.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'320px fits');await r.screenshot({path:'qa/v7/reduced-core.png'});console.log(errors);ok(errors.length===0,'No runtime errors');await fs.writeFile('qa/v7/checks.json',JSON.stringify({checks,errors},null,2));console.log('PASS',checks.length);await browser.close();

