import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';import {saveEntry} from './panel-store.mjs';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const {chromium}=createRequire(import.meta.url)('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'ensylmz-panel-test-'));await fs.mkdir(path.join(temp,'src/data'),{recursive:true});await fs.mkdir(path.join(temp,'src/media'));await fs.mkdir(path.join(temp,'dist/assets'),{recursive:true});await fs.writeFile(path.join(temp,'dist/assets/content.json'),JSON.stringify({projects:[]}));
const png='data:image/png;base64,'+(await fs.readFile('src/media/rokka-orijinal.png')).toString('base64');const input={type:'project',slug:'test-proje',brand:'Test',title:'Test projesi',filter:'web',period:'2026',summary:'Özet',goal:'Amaç',role:'Kapsam',work:'Tasarım | Yapılan çalışma',cover:png,logo:png,gallery:[{image:png,caption:'Detay'}]};let count=0;
await saveEntry(temp,input);const stored=JSON.parse(await fs.readFile(path.join(temp,'src/data/panel-content.json')));if(stored.projects[0].work[0][0]!=='Tasarım'||stored.projects[0].gallery.length!==1)throw Error('Project storage');count++;
await saveEntry(temp,{type:'logo',name:'Test Logo',category:'Tasarım',image:png});count++;
try{await saveEntry(temp,{...input,slug:'../escape'});throw Error('Accepted invalid slug')}catch(e){if(e.message==='Accepted invalid slug')throw e;count++;}
await fs.rm(temp,{recursive:true,force:true});
const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/panel/');await p.waitForSelector('#persistent-panel');if(await p.locator('form[data-type=project] textarea').count()!==4)throw Error('Fields missing');count++;
const reject=await p.request.post('http://127.0.0.1:4173/api/panel',{data:input,headers:{Origin:'https://example.com'}});if(reject.status()!==403)throw Error('Origin guard');count++;
const data=await p.request.get('http://127.0.0.1:4173/api/panel');if(!data.ok())throw Error('API unavailable');count++;
const store='src/data/panel-content.json',prior=await fs.readFile(store).catch(()=>null),before=new Set(await fs.readdir('src/media'));const testSlug='qa-panel-'+Date.now();
try{const saved=await p.request.post('http://127.0.0.1:4173/api/panel',{data:{...input,slug:testSlug},headers:{Origin:'http://127.0.0.1:4173'}});if(!saved.ok())throw Error(await saved.text());count++;await p.goto('http://127.0.0.1:4173/projeler/'+testSlug+'/');if(await p.locator('.project-overview h2').textContent()!=='Neyeodaklandım?'||await p.locator('.work-list article').count()!==1)throw Error('Generated project template');count++;await p.goto('http://127.0.0.1:4173/referanslar/');if(!await p.locator('a[href="/projeler/'+testSlug+'/"]').count())throw Error('Reference list missing');count++;}
finally{if(prior)await fs.writeFile(store,prior);else await fs.unlink(store).catch(()=>{});for(const name of await fs.readdir('src/media'))if(!before.has(name)&&/^panel-[a-f0-9-]+\.(png|jpg|webp)$/.test(name))await fs.unlink(path.join('src/media',name));await fs.rm(path.join('dist/projeler',testSlug),{recursive:true,force:true});await promisify(execFile)(process.execPath,['scripts/build.mjs'],{windowsHide:true});}
await p.goto('http://127.0.0.1:4173/panel/');
if(errors.length)throw Error(errors.join('\n'));await fs.mkdir('qa/panel',{recursive:true});await p.screenshot({path:'qa/panel/panel.png',fullPage:true});await b.close();console.log('PASS',count,'panel checks');
