import {createRequire} from 'node:module';import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await fs.mkdir('qa/v4',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,n)=>{if(!v)throw Error(n);checks.push(n)};
await page.goto('http://127.0.0.1:4173/');await page.waitForTimeout(2800);ok(await page.locator('.orbit-sound').isVisible()===false,'Sound control hidden outside projects');const before=await page.locator('#astronaut').boundingBox();await page.locator('#astronaut').click();await page.waitForTimeout(2700);const after=await page.locator('#astronaut').boundingBox();ok(Math.abs(after.x-before.x-75)<5,'First click moves seating position');await page.locator('#astronaut').click();await page.waitForTimeout(1200);ok(await page.locator('.laser-splat').count()===1,'Second click shoots one energy mark');await page.screenshot({path:'qa/v4/header-shot.png'});await page.waitForTimeout(2500);ok(Math.abs((await page.locator('#astronaut').boundingBox()).x-before.x)<5,'Second gag returns to original position');
await page.locator('.scene-card').first().scrollIntoViewIfNeeded();await page.waitForTimeout(850);ok(await page.locator('.ground-rift').count()>0,'Project entrance opens ground');await page.waitForTimeout(1000);ok(await page.locator('.orbit-sound').isVisible(),'Sound control appears in references');await page.screenshot({path:'qa/v4/references.png'});
await page.locator('.about-teaser').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-80));await page.waitForTimeout(1700);ok(['walk','stumble'].includes(await page.locator('#astronaut').getAttribute('data-pose')),'About autonomous glyph walk');await page.screenshot({path:'qa/v4/glyph-walk.png'});await page.waitForTimeout(4100);ok(await page.locator('#astronaut').getAttribute('data-pose')==='look','About settles beside link');ok(!await page.locator('.orbit-sound').isVisible(),'Sound control leaves outside references');
await page.locator('[data-scene=services]').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-160));await page.waitForTimeout(350);const states=await page.locator('.push-row').evaluateAll(es=>es.map(e=>e.dataset.delivery));ok(states.includes('waiting')&&states.includes('pushing'),'Helpers arrive at staggered times');await page.screenshot({path:'qa/v4/services-delivery.png'});await page.waitForTimeout(3000);ok(await page.locator('.push-row').evaluateAll(es=>es.every(e=>e.dataset.delivery==='done')),'All four deliveries finish without scrolling');
await page.locator('.footer').scrollIntoViewIfNeeded();await page.waitForTimeout(1400);await page.locator('#astronaut').click();await page.waitForTimeout(3800);ok(await page.evaluate(()=>scrollY)<5,'Footer rocket preserved');ok(await page.locator('#astronaut').getAttribute('data-pose')==='sit','Ceiling recovery preserved');
const mobile=await ctx.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.setViewportSize({width:390,height:844});await mobile.goto('http://127.0.0.1:4173/');await mobile.waitForTimeout(2700);await mobile.locator('#astronaut').click();await mobile.waitForTimeout(2600);ok(await mobile.locator('#astronaut').getAttribute('data-pose')==='sit','Mobile tap gag finishes');for(const s of ['.scene-card','.about-teaser','[data-scene=services]','.identity-section']){await mobile.locator(s).first().scrollIntoViewIfNeeded();await mobile.waitForTimeout(1000);ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile fits '+s);}await mobile.screenshot({path:'qa/v4/mobile.png'});
const rc=await browser.newContext({reducedMotion:'reduce',viewport:{width:320,height:740}}),rp=await rc.newPage();await rp.goto('http://127.0.0.1:4173/');ok(await rp.locator('.push-row h3').first().evaluate(e=>getComputedStyle(e).opacity==='1'),'Reduced motion headings visible');ok(errors.length===0,'No runtime errors');await fs.writeFile('qa/v4/checks.json',JSON.stringify({checks,errors},null,2));console.log('PASS',checks.length);await browser.close();

